### ISSUE TITLE
why use memory flag in buffer flag

### ISSUE THREAD

**Issue by fuhaijin** [ARM-software/vktrace-arm#3]
file: vktrace/vktrace_replay/vkreplay_vkreplay.cpp 
func: manually_replay_vkCreateBuffer
![image](https://user-images.githubusercontent.com/19526027/163296013-d05b52b5-0303-4fcc-8f39-592087094e1d.png)
const_cast<VkBufferCreateInfo*>(pPacket->pCreateInfo)->flags = pPacket->pCreateInfo->flags & ~**VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR**;
why not **VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT**？

**Comment by per-mathisen-arm** [comment]
Looks like this has been fixed: https://github.com/ARM-software/vktrace-arm/blob/master/vktrace/vktrace_replay/vkreplay_vkreplay.cpp#L1926
