### ISSUE TITLE
vktrace segment fault built by yocto langdale, gcc version 12.2.0

### ISSUE THREAD

**Issue by pleasurefish** [ARM-software/vktrace-arm#5]
#0  __pthread_clockjoin_ex (threadid=0, thread_return=0x7fef27e8b0, clockid=0, abstime=0x0, block=true) at pthread_join_common.c:43
#1  0x0000005555588810 in vktrace_linux_sync_wait_for_thread (pThread=0x5555690ee0 <traceid>)
    at vktrace-arm/vktrace/vktrace_common/vktrace_platform.c:435
#2  0x0000005555581ac0 in Process_RunWatchdogThread (_procInfoPtr=0x7ffffff8d8) at vktrace-arm/vktrace/vktrace_trace/vktrace_process.cpp:159
#3  0x0000007ff7b0e28c in start_thread (arg=0x7ffffff76f) at pthread_create.c:442
#4  0x0000007ff7b7659c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79

**Comment by per-mathisen-arm** [comment]
We would need a lot more details than that. For instance, what content is this, what were you doing when it crashed, and any interesting output from it on the cmd line?

**Comment by pleasurefish** [comment]
i have enabled the Thread Sanitizer to debug the crash. below is the what i have done on my board.
```
root@localhost:~/vktrace# find .
./layersvt
./layersvt/VkLayer_device_simulation.json
./layersvt/libVkLayer_api_cost.so
./layersvt/libVkLayer_device_simulation.so
./layersvt/libVkLayer_api_dump.so
./layersvt/VkLayer_hwcprofiler.json
./layersvt/libVkLayer_screenshot.so
./layersvt/libVkLayer_monitor.so
./layersvt/VkLayer_emptydriver.json
./layersvt/libVkLayer_hwcprofiler.so
./layersvt/VkLayer_screenshot.json
./layersvt/VkLayer_monitor.json
./layersvt/VkLayer_api_cost.json
./layersvt/libVkLayer_emptydriver.so
./layersvt/VkLayer_api_dump.json
./layersvt/VkLayer_vktrace_layer.json
./bin
./bin/libVkLayer_vktrace_layer.so
./bin/libVkLayer_screenshot.so
./bin/vktrace
./bin/vkreplay
./bin/VkLayer_screenshot.json
./bin/vktracedump
./bin/VkLayer_vktrace_layer.json
./bin/libvkdisplay_wayland.so
root@localhost:~/vktrace#export VK_LAYER_PATH=/home/root/vktrace/layersvt:$VK_LAYER_PATH
root@localhost:~/vktrace#export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump
root@localhost:~/vktrace#vktrace -p /usr/bin/vkcube-wayland -a "--c 30" -o cube.vktrace
vktrace info: Tracing with v3.4 dev unofficial
Selected GPU 0: Mali-G52, type: IntegratedGpu
==1749==ThreadSanitizer: dup thread with used id 0x0
```

**Comment by per-mathisen-arm** [comment]
I cannot quite reproduce this here, but I also do not have a similar setup as you. But don't need to run vktrace -p to make traces, you can skip that and with VK_INSTANCE_LAYERS set it should still start tracing as long as you use the Vulkan loader, and this avoids some issues that I've seen.

**Comment by pleasurefish** [comment]
we use gfxreconstruct now.
